name: aes
version: 1.0.0
description: A new Get Server application.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  crypto: ^3.0.3
  encrypt: ^5.0.3
  server_nano: ^1.2.0

dev_dependencies: 
  pedantic: 1.11.1
  test: 1.25.2
  flutter_lints: 3.0.1

